name: stock-trading-app
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_USERNAME/stock-trading-app
    branch: main
  run_command: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: GROQ_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GEMINI_API_KEY
    scope: RUN_TIME
    type: SECRET
